services:
  postgres:
    image: postgres:16
    container_name: dev_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_DEV_USER}
      POSTGRES_PASSWORD: ${DB_DEV_PASSWORD}
      POSTGRES_DB: ${DB_DEV_NAME}
    volumes:
      - dev_pgdata:/var/lib/postgresql/data
    networks:
      - dev_net

  backend:
    container_name: dev_todo_backend
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_DEV_PORT}
      DB_NAME: ${DB_DEV_NAME}
      DB_USER: ${DB_DEV_USER}
      DB_PASSWORD: ${DB_DEV_PASSWORD}
    expose:
      - "8080"
    networks:
      - dev_net
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - dev_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev_pgadmin
    ports:
      - "127.0.0.1:8088:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEV_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEV_PASSWORD}
    networks:
      - dev_net

  

