services:
  postgres:
    image: postgres:16
    container_name: prod_postgres
    environment:
      POSTGRES_USER: ${DB_PROD_USER}
      POSTGRES_PASSWORD: ${DB_PROD_PASSWORD}
      POSTGRES_DB: ${DB_PROD_NAME}
    volumes:
      - prod_pgdata:/var/lib/postgresql/data
    networks:
      - prod_net

  backend:
    container_name: prod_todo_backend
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PROD_PORT}
      DB_NAME: ${DB_PROD_NAME}
      DB_USER: ${DB_PROD_USER}
      DB_PASSWORD: ${DB_PROD_PASSWORD}
    expose:
      - "8080"
    networks:
      - prod_net
  nginx:
    image: nginx:latest
    container_name: prod_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - prod_net
